### ISSUE TITLE
Avoid deadlocks

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/statscompiler#1]
processor and statscompiler seem to interfere

**Comment by schneefux** [comment]
It looks like the deadlocks are caused by joblib, which is expected.

**Comment by kvahuja** [comment]
deadlocks are generally bad. can you document why they are acceptable in this case?

**Comment by schneefux** [comment]
Workers race for jobs. Every worker tries to update a job status from "open" to "running", but only the one that succeeds gets this particular job and the others retry with a different one. There is a part in the Postgres docs, it uses the "serialization" transaction level which means that table locks prevent concurrent access. Serialization errors need to be expected. The Postgres logs unfortunately log every single serialization problem.

Do you have a suggestion or do you think that this is the best solution?

I can decrease the chance of deadlocks by randomly picking jobs from the list of jobs with the highest priority.

**Comment by schneefux** [comment]
Correction. I just talked about `SerializationError`s, the Deadlocks I got were different and need to be fixed, see vainglorygame/processor/issues/35.
